CREATE TABLE IF NOT EXISTS fortunes (
  id BIGSERIAL PRIMARY KEY,
  slug VARCHAR(80) NOT NULL UNIQUE,
  title VARCHAR(120) NOT NULL,
  subtitle VARCHAR(200) NOT NULL,
  price INTEGER NOT NULL,
  icon VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS stories (
  id BIGSERIAL PRIMARY KEY,
  slug VARCHAR(80) NOT NULL UNIQUE,
  title VARCHAR(120) NOT NULL,
  subtitle VARCHAR(200) NOT NULL,
  price INTEGER NOT NULL CHECK (price >= 0),
  icon VARCHAR(20) NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE
);
